version: "3.2"

services: 
    rocker:
        image: obedaeg/rstudio-mysql
        ports:
            - "8787:8787"
        environment: 
            PASSWORD: 123
        volumes: 
            - ./src:/home/rstudio/src
        links:
            - db

    db:
        image: mysql
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root123
            MYSQL_DATABASE: academatica_db
        volumes:
            - ./init:/docker-entrypoint-initdb.d/:ro