---
title: "Academatica"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
--- 


```{r}
if(!require("RMySQL")) install.packages("RMySQL")
if(!require("flexdashboard")) install.packages("flexdashboard")
if(!require("dplyr")) install.packages("dplyr")
if(!require("readxl")) install.packages("readxl")
if(!require("DT")) install.packages("DT")
if(!require("ggplot2")) install.packages("ggplot2")


library(RMySQL)
library("DBI")
library(flexdashboard)
library(readr)
library(dplyr)
library(DT)
library(ggplot2)
```


```{r}
mydb = dbConnect(MySQL(), user = 'root', password = 'root123', dbname='academatica_db', host = '192.168.144.2')


stats<- as.data.frame(mydb%>% tbl("stats"))
videos<- as.data.frame(mydb%>% tbl("videos"))
metadata<- as.data.frame(mydb%>% tbl("metadata"))
```

# Analisis Exploratorio


##
```{r}
meta <- metadata %>% 
  subset(select = c(id,title)) %>% 
  arrange(id)


vids <- videos %>% 
  subset(select = c(contentDetailsvideoId,contentDetailsvideoPublishedAt)) %>%
  rename(id = contentDetailsvideoId, date = contentDetailsvideoPublishedAt) %>% 
  arrange(id)

vidsData <- merge(vids,stats, by = "id")

vidsData <- merge(vidsData,meta, by = "id")

vidsData <- vidsData %>% 
  transform(date = as.Date(date),
            viewCount = as.numeric(viewCount),
            likeCount = as.numeric(likeCount),
            dislikeCount = as.numeric(dislikeCount),
            favoriteCount = as.numeric(favoriteCount),
            commentCount = as.numeric(commentCount))


DT::datatable(vidsData)
```


## videos

###

```{r}
valueBox(nrow(data), 
         caption = "Total de videos",
         icon = "fa-youtube")
```


###

```{r}
valueBox(sum(vidsData$viewCount), 
         caption = "Total de views",
         icon = "fa-eye")
```

###

```{r}
valueBox(sum(vidsData$likeCount),
         caption = "Total de likes",
         icon = "fa-thumbs-up")
```


# views

##

###

```{r}
valueBox(mean(vidsData$viewCount), 
         caption = "Promedio de views",
         icon = "fa-eye")
```


###

```{r}
valueBox(max(vidsData$viewCount), 
         caption = "Maximo de views",
         icon = "fa-arrow-alt-circle-up",
         color = "success")
```

###

```{r}
valueBox(min(vidsData$viewCount), 
         caption = "Minimo de views",
         icon = "fa-arrow-alt-circle-down",
         color = "warning")
```


Row {data-height=350}
-------------------------------------
    

### Views a traves del tiempo 

```{r}
options(scipen = 999)
ggplot(data = vidsData, aes(x = date, y = viewCount))+
  geom_line(color = "#00AFBB", size = 2)
```


### Distribucion de las views 

```{r}

vidsData %>% 
  ggplot(aes(x=viewCount)) + geom_density()

```


# likes

##

###

```{r}
valueBox(mean(vidsData$likeCount),
         caption = "Promedio de likes",
         icon = "fa-thumbs-up")
```

###

```{r}
valueBox(max(vidsData$likeCount), 
         caption = "Maximo de likes",
         icon = "fa-arrow-alt-circle-up",
         color = "success")
```

###

```{r}
valueBox(min(vidsData$likeCount), 
         caption = "Minimo de likes",
         icon = "fa-arrow-alt-circle-down",
         color = "warning")
```



Row {data-height=350}
-------------------------------------
    


### Likes a traves del tiempo 
```{r}
ggplot(data = vidsData, aes(x = date, y = likeCount))+
  geom_line(color = "#00AFBB", size = 2)
```

### Distribucion de las likes 


```{r}

vidsData %>% 
  ggplot(aes(x=likeCount)) + geom_density()

```














